apiVersion: v1
kind: Service
metadata:
  name: task-management-backend-service
  namespace: default
  labels:
    app: task-management-backend
    component: api
    environment: dev
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: metrics
  selector:
    app: task-management-backend
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

