apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-management-backend
  namespace: default
  labels:
    app: task-management-backend
    component: api
    environment: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: task-management-backend-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: task-management-backend-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: task-management-backend
  namespace: default
roleRef:
  kind: Role
  name: task-management-backend-role
  apiGroup: rbac.authorization.k8s.io

