apiVersion: v1
kind: LimitRange
metadata:
  name: task-management-limits
  namespace: default
  labels:
    app: task-management
    component: limit-range
    environment: dev
spec:
  limits:
  # Container limits
  - type: Container
    default:
      memory: "512Mi"
      cpu: "500m"
    defaultRequest:
      memory: "256Mi"
      cpu: "250m"
    min:
      memory: "128Mi"
      cpu: "100m"
    max:
      memory: "2Gi"
      cpu: "2000m"
    maxLimitRequestRatio:
      memory: 4
      cpu: 4
  
  # Pod limits
  - type: Pod
    min:
      memory: "256Mi"
      cpu: "250m"
    max:
      memory: "4Gi"
      cpu: "4000m"
  
  # Persistent volume claim limits
  - type: PersistentVolumeClaim
    min:
      storage: "1Gi"
    max:
      storage: "100Gi"

